### ISSUE TITLE
should add Seize/Cont functionality (only Linux)

### ISSUE THREAD

**Issue by haxkor** [vstinner/python-ptrace#51]
Hi, this is my first time posting an Issue, apologies if its done in an incorrect way.

I really like this library. I extended it a bit to support using PTRACE_SEIZE and the various upsides this brings, however I can only test on my 64 Bit Linux and dont really now the constants values for other OSes nor can I test it. 
Should I provide my fix even though it wont work on BSD?

Thank you for providing the library!

**Comment by vstinner** [comment]
I don't really maintain python-ptrace anymore, so if you want a feature ,you have to write it ;-)

It already has feature which are not available on all platforms.

**Comment by haxkor** [comment]
I assume by "i dont maintain" you mean that you will not accept pull requests.

If anyone is reading this and wants PTRACE_SEIZE support, hit me up.

**Comment by vstinner** [comment]
I can review pull requests ;-) By the way, I just released python-ptrace 0.9.5 since there was an unreleased fix.

**Comment by haxkor** [comment]
Alright! :)
