### ISSUE TITLE
Closing file descriptors

### ISSUE THREAD

**Issue by spoutn1k** [vstinner/python-ptrace#54]
What is the rationale behind the [closing of file descriptors](https://github.com/vstinner/python-ptrace/blob/be9709dec86205001d12cffb583264227e533b97/ptrace/debugger/child.py#L97-L104) before executing a child ?

I noticed this pythonic behaviour in the `subprocess` module for Windows portability, but is there a case against an option to turn that off while creating a child ? `strace` does not do that, and my use case relies on opened file descriptors to communicate.

I can provide a pull request for that too, just wanted to know if there is a particular case this is required.

Sorry for the spam on an old repo !

**Comment by vstinner** [comment]
> is there a case against an option to turn that off while creating a child

It sounds reasonable to me to have option to not close file descriptors and/or pass file descriptors.

Python subprocess API now has a pass_fds parameter.

**Comment by spoutn1k** [comment]
Closing issue as PR merged.
