### ISSUE TITLE
error message method

### ISSUE THREAD

**Issue by ian910297** [vstinner/python-ptrace#56]
Why not display error message in the same way? Some functions use "print(xxxx, file=stderr)" directly, and the others use "error(xxxxxx)". 

Besides, "file=stderr" is gone in python3, it should be rewritten.

**Comment by spoutn1k** [comment]
Can you be more precise ? I see no use of `print()` in the whole module, only in the scripts, which do not use the same logging methods.

Besides, where did that come from ? The `file` option is [supported in the python 3.8.5  docs](https://docs.python.org/3/library/functions.html#print).

**Comment by spoutn1k** [comment]
The `file` option is present in python3.11. No need to rewrite that.
