### ISSUE TITLE
Plan to add aarch64 support?

### ISSUE THREAD

**Issue by ggardet** [vstinner/python-ptrace#57]
Currently on 32-bit arm is supported. Do you plan to add `aarch64` support?
`uname` would return `aarch64` instead of `arm`*

**Comment by vstinner** [comment]
Pull requests are welcomed! :-)

**Comment by spoutn1k** [comment]
It's planned down the line, but I have no real way to test. Would you be interested in it ?

**Comment by hrw** [comment]
Not tested.

**Comment by spoutn1k** [comment]
@ggardet can you test [my patch](https://github.com/spoutn1k/python-ptrace/tree/aarch64) ? The test are outdated as some syscalls do not exist in AArch64, I see correct results from manual comparisons. I have not tested modifying the register's contents, but it should be functionnal.

**Comment by ggardet** [comment]
> @ggardet can you test [my patch](https://github.com/spoutn1k/python-ptrace/tree/aarch64) ? The test are outdated as some syscalls do not exist in AArch64, I see correct results from manual comparisons. I have not tested modifying the register's contents, but it should be functionnal.

I tested it and commented directly on https://github.com/vstinner/python-ptrace/pull/59

**Comment by spoutn1k** [comment]
AArch64 support added with #59.
