### ISSUE TITLE
python-ptrace fork support

### ISSUE THREAD

**Issue by spoutn1k** [vstinner/python-ptrace#66]
Hey ! I was checking out the new commits when I came accross this issue:

Using this script:
```py
python-ptrace> cat ../test.py 
#!/usr/bin/env python
import subprocess

message = ["Message", "à", "écrire"]

processes = [subprocess.Popen(["echo", mot]) for mot in message]
[proc.wait() for proc in processes]
```

I get the following from `python-ptrace`:
```
python-ptrace> ./strace.py ../test.py
[ ... ]
Debugger error: [ProcessSignal] Signal signal<133>
Traceback (most recent call last):
  File "/home/jb/Projects/python-ptrace/./strace.py", line 259, in _main
    exitcode = self.runDebugger()
  File "/home/jb/Projects/python-ptrace/./strace.py", line 243, in runDebugger
    return self.syscallTrace(process)
  File "/home/jb/Projects/python-ptrace/./strace.py", line 188, in syscallTrace
    self.syscall(event.process)
  File "/home/jb/Projects/python-ptrace/./strace.py", line 193, in syscall
    syscall = state.event(self.syscall_options)
  File "/home/jb/Projects/python-ptrace/ptrace/debugger/syscall_state.py", line 15, in event
    return self.exit()
  File "/home/jb/Projects/python-ptrace/ptrace/debugger/syscall_state.py", line 40, in exit
    self.process.waitSignals(SIGTRAP)
  File "/home/jb/Projects/python-ptrace/ptrace/debugger/process.py", line 736, in waitSignals
    return self.debugger.waitSignals(*signals, **{'pid': self.pid})
  File "/home/jb/Projects/python-ptrace/ptrace/debugger/debugger.py", line 209, in waitSignals
    raise event
ptrace.debugger.ptrace_signal.ProcessSignal: Signal signal<133>
Terminate <PtraceProcess #2181>
```

This does not happen when using `strace.py python test.py`, but does when launching `strace.py --fork python test.py`.

I remember the documentation specifically stating lack of support for forks, has this been added ?

**Comment by neok-m4700** [comment]
My output, with and without `--fork`:

```bash
$ strace.py -o /dev/null ./test.py
Message
à
écrire
$ strace.py -o /dev/null --fork ./test.py
Message
à
écrire
```

Simple fork example:
```python
#!/usr/bin/env python
import time
import os

if (pid := os.fork()) == 0:
    print('[child] pid=', os.getpid())
    time.sleep(1)
else:
    print('[parent] pid=', os.getpid(), 'child_pid=', pid)
    os.waitpid(pid, 0)
```

```bash
$ strace.py --fork -e clone,write ./a.py
execve(<...>/a.py, ['<...>/a.py'], [/* 40 vars */]) = 2193415
*** New process 2193416 ***
[2193415] clone(<SIGCHLD|CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|17> (18874385), 0, NULL, <2193415>, 0) = 2193416 (0x0000000000217808)
[parent] pid= 2193415 child_pid= 2193416
[child] pid= 2193416
[2193415] write(1, '[parent] pid= 2193415 child_pid= 2193416\n', 41) = 41 (0x0000000000000029)
[2193416] write(1, '[child] pid= 2193416\n', 21)   = 21 (0x0000000000000015)
*** Process 2193416 exited normally ***
------------------------------------------------------------
PID: 2193415
Signal: SIGCHLD
Child process 2193416 exited normally
Signal sent by user 1000
------------------------------------------------------------
*** Process 2193415 exited normally ***

$ strace.py -e clone,write ./a.py
execve(<...>/a.py, ['<...>/a.py'], [/* 40 vars */]) = 2193484
[child] pid= 2193485
clone(<SIGCHLD|CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|17> (18874385), 0, NULL, <2193484>, 0) = 2193485 (0x000000000021784d)
[parent] pid= 2193484 child_pid= 2193485
write(1, '[parent] pid= 2193484 child_pid= 2193485\n', 41) = 41 (0x0000000000000029)
------------------------------------------------------------
PID: 2193484
Signal: SIGCHLD
Child process 2193485 exited normally
Signal sent by user 1000
------------------------------------------------------------
*** Process 2193484 exited normally ***
```

The line `[2193416] write(1, '[child] pid= 2193416\n', 21)   = 21 (0x0000000000000015)` whows that the child process is successfully traced.

**Comment by spoutn1k** [comment]
Great then forking is supported.

The issue stands as `Popen` uses `clone`, and that `SIGCHLD`s are not handled in this case. I figure an unhandled exception is not a desirable outcome. Can you try launching `strace.py` without suppressing its output to check if that error is only on my two machines ?

**Comment by neok-m4700** [comment]
Here is the log: [log](https://gist.github.com/neok-m4700/267242115cae05cd7526ff2a475eb723)
`strace.py --trace-clone --trace-exec --fork -o log ./test.py`

**Comment by spoutn1k** [comment]
`strace.py --trace-clone --trace-exec --fork ./test.py` gives me the same.

There is a unhandled exception using `strace.py ./test.py`. Should this be intended behaviour ?

**Comment by neok-m4700** [comment]
In https://github.com/vstinner/python-ptrace/commit/00e93636934c4d1cc60809120f60784e491d9898, I added an exitcode to `strace.py` using `128 + SIGNUM` when the process is killed by a signal.

So your line showing `ptrace.debugger.ptrace_signal.ProcessSignal: Signal signal<133>`
looks like `128 + SIGTRAP = 128 + 5 = 133`.

The ProcessSignal should be caught in the [mainloop](https://github.com/vstinner/python-ptrace/blob/master/strace.py#L175) of `syscallTrace`.

**Comment by spoutn1k** [comment]
The exit code is not present:

```
python-ptrace> strace.py ./test.py
[ ... ]
openat(AT_FDCWD, '/usr/lib/locale/locale-archive', O_RDONLY|O_CLOEXEC (0o2000000)) = 3
fstat(3, 0x00007ff2a4f50600)             = 0
mmap(0, 3045936, <PROT_READ> (1), 2, 3, 0) = 140680121425920 (0x00007ff2a4aa2000)
close(3)                                 = 0
Debugger error: [ProcessSignal] Signal signal<133>
Traceback (most recent call last):
  File "/home/jb/.local/lib/python3.9/site-packages/python_ptrace-0.9.8-py3.9.egg/EGG-INFO/scripts/strace.py", line 259, in _main
  File "/home/jb/.local/lib/python3.9/site-packages/python_ptrace-0.9.8-py3.9.egg/EGG-INFO/scripts/strace.py", line 243, in runDebugger
  File "/home/jb/.local/lib/python3.9/site-packages/python_ptrace-0.9.8-py3.9.egg/EGG-INFO/scripts/strace.py", line 188, in syscallTrace
  File "/home/jb/.local/lib/python3.9/site-packages/python_ptrace-0.9.8-py3.9.egg/EGG-INFO/scripts/strace.py", line 193, in syscall
  File "/home/jb/.local/lib/python3.9/site-packages/python_ptrace-0.9.8-py3.9.egg/ptrace/debugger/syscall_state.py", line 15, in event
    return self.exit()
  File "/home/jb/.local/lib/python3.9/site-packages/python_ptrace-0.9.8-py3.9.egg/ptrace/debugger/syscall_state.py", line 40, in exit
    self.process.waitSignals(SIGTRAP)
  File "/home/jb/.local/lib/python3.9/site-packages/python_ptrace-0.9.8-py3.9.egg/ptrace/debugger/process.py", line 735, in waitSignals
    return self.debugger.waitSignals(*signals, **{'pid': self.pid})
  File "/home/jb/.local/lib/python3.9/site-packages/python_ptrace-0.9.8-py3.9.egg/ptrace/debugger/debugger.py", line 209, in waitSignals
    raise event
ptrace.debugger.ptrace_signal.ProcessSignal: Signal signal<133>
Terminate <PtraceProcess #9193>
python-ptrace> echo $?
1
```

Plus the process is never killed by this signal ? Isn't the default `SIGCHLD` handling to ignore it ?

**Comment by spoutn1k** [comment]
Also this is all on [43cdc301cf40b29e2eb4f8ac634342e049e14e5d](https://github.com/vstinner/python-ptrace/commit/43cdc301cf40b29e2eb4f8ac634342e049e14e5d):

```
python-ptrace> git show
commit 43cdc301cf40b29e2eb4f8ac634342e049e14e5d (HEAD -> master, origin/master, origin/HEAD)
Merge: 149fc07 ded10e3
Author: Victor Stinner <vstinner@python.org>
Date:   Wed Feb 3 16:51:38 2021 +0100

    Merge pull request #64 from neok-m4700/disasm
    
    FIX: failing test_where if HAS_DISASSEMBLER

```

**Comment by neok-m4700** [comment]
What's the output using 26af6802b16af1e6439b994c1bc579c3ff079c74 ?

**Comment by spoutn1k** [comment]
You cannot replicate this behaviour ?

The output is exactly the same in [`26af680`](https://github.com/vstinner/python-ptrace/commit/26af6802b16af1e6439b994c1bc579c3ff079c74). I am not saying it is a new error, I am saying it is an error.

```
python-ptrace> uname -a
Linux arcIV 5.10.10-arch1-1 #1 SMP PREEMPT Sat, 23 Jan 2021 23:59:48 +0000 x86_64 GNU/Linux
python-ptrace> echo $SHELL
/bin/bash
```

**Comment by neok-m4700** [comment]
No, I cannot replicate this error, your example runs fine on my machine using latest 43cdc301cf40b29e2eb4f8ac634342e049e14e5d.
> ```shell
> $ strace.py -o /dev/null ./test.py
> Message
> à
> écrire
> $ strace.py -o /dev/null --fork ./test.py
> Message
> à
> écrire
> ```

What is strange is that the event raised is a `ProcessSignal`, so this https://github.com/vstinner/python-ptrace/blob/master/ptrace/debugger/debugger.py#L204 should not raise.

**Comment by spoutn1k** [comment]
It is a `ProcessSignal` so this line has no effect. It is raised as the signal number is [not in the expected list](https://github.com/vstinner/python-ptrace/blob/43cdc301cf40b29e2eb4f8ac634342e049e14e5d/ptrace/debugger/debugger.py#L206-L209).

**Comment by neok-m4700** [comment]
My bad ;), wrong line number read.

With these `print(...)` added:
```python
        pid = kw.get('pid', None)
        while True:
            print(signals)
            event = self._wait_event(pid)
            if not isinstance(event, ProcessSignal):
                raise event
            signum = event.signum
            print(signum)
            if signum in signals or not signals:
                print('return event', event)
                return event
            print('raised event', event)
            raise event
```

```
return event Signal signal<133>
(133,)
133
return event Signal signal<133>
(<Signals.SIGTRAP: 5>,)
5
return event Signal SIGTRAP
execve('$PREFIX/bin/python', ...) = 0

[...]

(133,)
133
return event Signal signal<133>
brk(28442624)                            = 28442624 (0x0000000001b20000)
(133,)
17
raised event Signal SIGCHLD
------------------------------------------------------------
PID: 2250409
Signal: SIGCHLD
Child process 2250410 exited normally
Signal sent by user 1000
------------------------------------------------------------
```

**Comment by spoutn1k** [comment]
My `PtraceDebugger().use_sysgood` returns `True`.

```
[ ... ]
Signum: 133 Signals: (133,)
return event Signal signal<133>
Sysgood: True
Signum: 133 Signals: (<Signals.SIGTRAP: 5>,)
raised event Signal signal<133>
Debugger error: [ProcessSignal] Signal signal<133>
Traceback (most recent call last):
  File "/home/jb/Projects/python-ptrace/./strace.py", line 259, in _main
    exitcode = self.runDebugger()
  File "/home/jb/Projects/python-ptrace/./strace.py", line 243, in runDebugger
    return self.syscallTrace(process)
  File "/home/jb/Projects/python-ptrace/./strace.py", line 188, in syscallTrace
    self.syscall(event.process)
  File "/home/jb/Projects/python-ptrace/./strace.py", line 193, in syscall
    syscall = state.event(self.syscall_options)
  File "/home/jb/Projects/python-ptrace/ptrace/debugger/syscall_state.py", line 15, in event
    return self.exit()
  File "/home/jb/Projects/python-ptrace/ptrace/debugger/syscall_state.py", line 40, in exit
    self.process.waitSignals(SIGTRAP)
  File "/home/jb/Projects/python-ptrace/ptrace/debugger/process.py", line 736, in waitSignals
    return self.debugger.waitSignals(*signals, **{'pid': self.pid})
  File "/home/jb/Projects/python-ptrace/ptrace/debugger/debugger.py", line 213, in waitSignals
    raise event
ptrace.debugger.ptrace_signal.ProcessSignal: Signal signal<133>
Terminate <PtraceProcess #11928>
```

It does fail expecting the wrong signal.

```py
python-ptrace> python
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from signal import SIGTRAP
>>> print(SIGTRAP)
Signals.SIGTRAP
>>> 5 in (SIGTRAP,)
True
```

**Comment by spoutn1k** [comment]
Wait what signal has the number `133` ? Your program printed the correct output when raising signal 17 (the correct number of `SIGCHLD`). Where is signal `133` coming from ?

**Comment by neok-m4700** [comment]
Can you post the full output somewhere ? I'd like to see the syscalls induced by `Popen()`: `fork()` or `clone()` ?

**Comment by spoutn1k** [comment]
Here is the [log](https://gist.github.com/spoutn1k/6cc0d16a872953685cfa155481bf5014).

**Comment by neok-m4700** [comment]
> Wait what signal has the number `133` ? Your program printed the correct output when raising signal `17` (the correct number of `SIGCHLD`). Where is signal `133` coming from ?

Might be `128 + 5 (SIGTRAP)`, added `signal_to_exitcode` [recently](https://github.com/vstinner/python-ptrace/blob/43cdc301cf40b29e2eb4f8ac634342e049e14e5d/ptrace/tools.py#L166).

**Comment by neok-m4700** [comment]
> Here is the [log](https://gist.github.com/spoutn1k/6cc0d16a872953685cfa155481bf5014).

Thanks, so this issue is in no way related to `fork()`, right ? Since the interpreter crashes before... So no race condition involved ?
Can we maybe narrow the test case down to `strace.py -- python -c 'print(1)'` ?

**Comment by spoutn1k** [comment]
Why would it wait for signal `133` and signal `5` then ?

> Thanks, so this issue is in no way related to fork(), right ?

`strace.py -- python -c 'print(1)'` works flawlessly. `strace.py --trace-clone --trace-exec --fork ./test.py` also works. The issue arises when a forking process is analysed without the appropriate options. I would say that it is.

**Comment by spoutn1k** [comment]
Modifying the following makes the issue go away:
```
python-ptrace> git diff
diff --git a/ptrace/debugger/syscall_state.py b/ptrace/debugger/syscall_state.py
index 798b21f..f5271ee 100644
--- a/ptrace/debugger/syscall_state.py
+++ b/ptrace/debugger/syscall_state.py
@@ -37,7 +37,7 @@ class SyscallState(object):
                 and not self.process.debugger.trace_exec:
             # Ignore the SIGTRAP after exec() syscall exit
             self.process.syscall()
-            self.process.waitSignals(SIGTRAP)
+            self.process.waitSignals(SIGTRAP, 133)
         syscall = self.syscall
         self.clear()
         return syscall
```

Figuring out why signals are received like this may be of use.

**Comment by neok-m4700** [comment]
Ok, thanks for clarifying that, it's a bit hard to debug, since we do not have the same outputs ...
What about the example mentioned before with a single fork(): `$ strace.py ./a.py`, what'ss your output, please ?
> ```python
> #!/usr/bin/env python
> import time
> import os
> 
> if (pid := os.fork()) == 0:
>     print('[child] pid=', os.getpid())
>     time.sleep(1)
> else:
>     print('[parent] pid=', os.getpid(), 'child_pid=', pid)
>     os.waitpid(pid, 0)
> ```

**Comment by neok-m4700** [comment]
> Figuring out why signals are received like this may be of use.

It depends how Popen() behaves on your os. If the shell is involved, then the `128 + N` exit code of the child might come from the bash shell  [When a command terminates on a fatal signal whose number is N, Bash uses the value 128+N as the exit status.](https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html)

**Comment by spoutn1k** [comment]
I understand, but an exit code would not translate to a signal number, would it ?

> EXIT: 133 = signal.SIGTRAP | 0x80 in waitSyscall

Okay this is the culprit ! Why is this here ? I'm only a casual `ptrace` user and this `sysgood` does not ring a bell.

**Comment by neok-m4700** [comment]
@spoutn1k, does this commit https://github.com/neok-m4700/python-ptrace/commit/68833a9e6fd9ee6353a3a1c9c7a65b2fe300991f solve your issue ?

**Comment by neok-m4700** [comment]
When you trace a process using `ptrace(2)`, the process receives `SIGTRAP` all the time, and twice for a [kernel syscall](https://man7.org/linux/man-pages/man2/ptrace.2.html)
> However, syscall-stops happen very often (twice per system call), and performing PTRACE_GETSIGINFO for every syscall-stop may be somewhat expensive.

When using `PTRACE_O_TRACESYSGOOD`, the expected signal is `SIGTRAP|0x80` hence `133`:
> PTRACE_O_TRACESYSGOOD (since Linux 2.4.6) When delivering system call traps, set bit 7 in the signal number (i.e., deliver SIGTRAP|0x80).  This makes it easy for the tracer to distinguish normal traps from those caused by a system call.

So the correct bahevior is to wait for a `SIGTRAP|0x80` upon exit of a syscall.

**Comment by spoutn1k** [comment]
I do not understand how removing the filter helps instead of doing [this](https://github.com/spoutn1k/python-ptrace/commit/61b2e4c43cc459fb4cc3679a294b57864791fa4f).

**Comment by neok-m4700** [comment]
> I do not understand how removing the filter helps instead of doing [this](https://github.com/spoutn1k/python-ptrace/commit/61b2e4c43cc459fb4cc3679a294b57864791fa4f).

Because if `PTRACE_O_TRACESYSGOOD` is set, then we are commited to distinguish between regular signals `SIGTRAP` and signals sent by the kernel `SIGTRAP|0x80`. So replacing with `self.process.waitSyscall()` boils down to `self.debugger.waitSignals(SIGTRAP OR SIGTRAP|0x80, pid=process.pid)`.

**Comment by spoutn1k** [comment]
From my understanding, `self.process.waitSyscall()` makes signals be [], which in turns waits for any kind of signal, instead of just the `SIGTRAP` signals we are expecting.

In other words, replacing with `self.process.waitSyscall()` boils down to `self.debugger.waitSignals(pid=process.pid)`, while adding `self.process.waitSyscall(SIGTRAP, SIGTRAP | 0x80)` does result in the expected `self.debugger.waitSignals(SIGTRAP, SIGTRAP|0x80, pid=process.pid)`

**Comment by neok-m4700** [comment]
I disagree:

`self.process.waitSyscall()` --> [`self.debugger.waitSyscall(self)`]( https://github.com/vstinner/python-ptrace/blob/master/ptrace/debugger/process.py#L739) = [`debugger.waitSyscall(process=self)`](https://github.com/vstinner/python-ptrace/blob/master/ptrace/debugger/debugger.py#L211) --> [`self.self.waitSignals(signum, pid=process.pid`)](https://github.com/vstinner/python-ptrace/blob/master/ptrace/debugger/debugger.py#L221).

**Comment by spoutn1k** [comment]
There has been a misunderstanding. We are talking about changing `self.process.waitSignals(...)`, NOT  `self.process.waitSyscall(...)`, correct ?

**Comment by neok-m4700** [comment]
> @spoutn1k, does this commit neok-m4700@68833a9 solve your issue ?

Glad we agree :), in the end, do you confirm that applying the proposed patch does solve the initial issue ?

**Comment by spoutn1k** [comment]
It does, got for it !
