### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by dvzrv** [vstinner/python-ptrace#84]
Hi! :wave: 

We're currently about to upgrade to Python 3.12 on Arch Linux.
This project is one of the projects still using the `imp` module in the latest released version.

Would it be possible to create a new release for this project, so that we can use that instead of applying https://github.com/vstinner/python-ptrace/commit/80e0c97a84eccb8b82737cf40b9c5581c20c245f?
That'd be much appreciated! :bow: 

cc @anthraxx (package maintainer)

**Comment by spoutn1k** [comment]
Hey ! Thank you for your work on Arch Linux !

Let me look into making a realease this evening.

**Comment by spoutn1k** [comment]
One less package using `imp` ! Closing now.
